name: hw_4
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0"

dependencies:
  cloud_firestore: ^0.13.4+1
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+2
  flutter:
    sdk: flutter
  fluttertoast: ^3.1.3
  provider: ^4.0.4
  # flutter_flipperkit: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
